import type { NextPage } from 'next';
import Head from 'next/head';
import { supabase } from '@/lib/supabaseClient';
import { gql, useQuery } from '@apollo/client';

import Editor from '@/components/Editor';
import Button from '@/components/common/Button';
import P from '@/components/common/P';

const POST_QUERY = gql`
  query MyQuery {
    getPostList {
      id
      text
      title
    }
  }
`;

const Home: NextPage = () => {
  // const user = supabase.auth.user();
  // const session = supabase.auth.session();

  // console.log({ user });

  const { data, loading, error } = useQuery(POST_QUERY);

  if (loading) {
    return <P variant="p1">Loading...</P>;
  }

  if (error) {
    return <p>something went wrong...</p>;
  }

  console.log(data);

  return (
    <div>
      <Head>
        <title>Modal Lesson 🚀</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-orange-600 text-7xl">MODAL LESSON VIBES! 🚀</h1>
      <h2 className="bg-primary text-6xl">asdf</h2>
      <h2 className="bg-secondary text-6xl">asdf</h2>
      <h2 className="bg-tertiary text-6xl">asdf</h2>
      <h2 className="bg-quaternary text-6xl">asdf</h2>
      <h2 className="bg-quinary text-6xl">asdf</h2>

      <Button variant="primary">Submit</Button>

      <h3 className="text-secondary">Hello World</h3>
      <Editor />
    </div>
  );
};

export default Home;
