import type { NextPage } from 'next';
import Head from 'next/head';

import { useForm } from 'react-hook-form';

import { GetServerSideProps } from 'next';

import Label from '@/components/common/Label';
import Input from '@/components/common/Input';
import Button from '@/components/common/Button';
import Heading from '@/components/common/Heading';

import { GoogleLoginButton } from 'react-social-login-buttons';

interface ProviderProps {
  providers: ProviderProps[];
  id: string;
  name: string;
  signInUrl: string;
  type: string;
  children: React.ReactNode;
}

const Login: NextPage<ProviderProps> = ({ providers }) => {
  const {
    register,
    handleSubmit,
    watch,
    formState: { errors },
  } = useForm();

  const onSubmit = (data: any) => console.log(data);

  console.log({ watch });

  return (
    <div className="flex flex-col items-center justify-center">
      <Head>
        <title>Modal Lesson 🚀</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col items-center justify-center shadow-2xl w-[300px] h-[400px] rounded-md border-2 border-black">
        <Heading variant="h4" className="mb-4">
          Welcome to Modal Lesson
        </Heading>

        <form onSubmit={handleSubmit(onSubmit)}>
          <Label htmlFor="email">Email</Label>
          <Input type="email" id="email" {...register('email', { required: true })} />
          {errors.email && <p className="text-red-400">{errors.email.message}</p>}

          <Label htmlFor="password">Password</Label>
          <Input id="password" type="password" {...register('password', { required: true })} />
          {errors.password && <p className="text-red-400">{errors.password.message}</p>}

          <Button variant="primary">Login</Button>
          <Button variant="primary">Register</Button>
        </form>
        <p>Or login with..</p>

        {Object.values(providers).map((provider) => (
          <div key={provider.name}>
            <GoogleLoginButton
              style={{ borderRadius: '5px', fontWeight: 'bold', fontSize: '1.1rem' }}
              onClick={() => signIn('google', { callbackUrl: '/' })}
            />
          </div>
        ))}
      </div>
    </div>
  );
};

export default Login;

export const getServerSideProps: GetServerSideProps = async () => {
  const providers = await getProviders();

  return {
    props: {
      providers,
    },
  };
};
