import { useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';

import { GetServerSideProps } from 'next';
import { signIn, getProviders } from 'next-auth/react';

import Label from '@/components/common/Label';
import Input from '@/components/common/Input';
import Button from '@/components/common/Button';

import { GoogleLoginButton } from 'react-social-login-buttons';

interface ProviderProps {
  providers: ProviderProps[];
  id: string;
  name: string;
  signInUrl: string;
  type: string;
  children: React.ReactNode;
}

const Login: NextPage<ProviderProps> = ({ providers }) => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');

  return (
    <div>
      <Head>
        <title>Modal Lesson 🚀</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Welcome to Modal Lesson</h1>
      <Label for="email">Email</Label>
      <Input type="email" name="email" value={email} onChange={(e) => setEmail(e.target.value)} />
      <Label for="password">Password</Label>
      <Input
        type="password"
        name="password"
        value={password}
        onChange={(e) => setPassword(e.target.value)}
      />
      <Button variant="primary">Login</Button>
      <Button variant="primary">Register</Button>
      <p>Or login with..</p>

      {Object.values(providers).map((provider) => (
        <div key={provider.name}>
          <GoogleLoginButton
            style={{ borderRadius: '5px', fontWeight: 'bold', fontSize: '1.1rem' }}
            onClick={() => signIn('google', { callbackUrl: '/' })}
          />
        </div>
      ))}
    </div>
  );
};

export default Login;

export const getServerSideProps: GetServerSideProps = async () => {
  const providers = await getProviders();

  return {
    props: {
      providers,
    },
  };
};
